name: shop_immi
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  get: ^4.6.6
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.4
  get_storage: ^2.1.1
  firebase_core: ^2.24.2
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.3.7
  lottie: ^2.7.0
  connectivity_plus: ^5.0.2
  firebase_storage: ^11.6.6
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.5
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/banners/promo-banner-3.png
    - assets/images/content/
    - assets/images/on_boarding_images/lotie.json
    - assets/images/on_boarding_images/sammy-line-delivery.gif
    - assets/images/on_boarding_images/sammy-line-no-connection.gif
    - assets/images/on_boarding_images/sammy-line-searching.gif
    - assets/images/on_boarding_images/sammy-line-shopping.gif
    - assets/images/products/
    - assets/images/reviews/
    - assets/logos/
    - assets/logos/TColors.java
    - assets/logos/t-store-splash-logo-black.png
    - assets/logos/t-store-splash-logo-white.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800