// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChjVLz0_YkcPI-MynISHC3QbLMT-Ond0A',
    appId: '1:265543683171:web:80c78a82dd6c0232fe3c56',
    messagingSenderId: '265543683171',
    projectId: 'shoppimmi',
    authDomain: 'shoppimmi.firebaseapp.com',
    storageBucket: 'shoppimmi.appspot.com',
    measurementId: 'G-TX2EZBMTRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY4gJLNb2MGCtIyKdnSvzPjhiNq4vMeEw',
    appId: '1:265543683171:android:4a86e62b41ed6a47fe3c56',
    messagingSenderId: '265543683171',
    projectId: 'shoppimmi',
    storageBucket: 'shoppimmi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqC0LCu0nMjjfrE4P8-jrIU3lSQE0UMAc',
    appId: '1:265543683171:ios:679c08c45762debdfe3c56',
    messagingSenderId: '265543683171',
    projectId: 'shoppimmi',
    storageBucket: 'shoppimmi.appspot.com',
    androidClientId: '265543683171-mg2hubsso6fusijh1vaofb5od4em3pkc.apps.googleusercontent.com',
    iosClientId: '265543683171-gebf4la567s0v14celrtkf6vcvukrkgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopImmi',
  );
}
